# Throwable 类

已实现接口：Serializable

已知子类：Error，Exception

## Error 类（错误）

**程序出现严重问题，程序无法解决**

例：函数拼写错误等

## Exception 类（异常）

​	**当程序出现异常时，jvm虚拟机会自动创建一个与该异常相关的异常类的对象，在被调用端没有任何处理的情况下异常对象会自动抛给调用端，如果调用端收到这个异常后也没有处理，会继续向上抛给jvm，jvm会打印这个异常对象所表示的信息。**

​	**某段代码出现异常后，其后代码不会被执行**

![image-20200608212612201](https://gitee.com/silent-passer/Img/raw/master/img/image-20200608212612201.png)

### 1. 运行时异常

#### 特点

​	**可编译通过，运行时报错**

#### 包含的异常类

​	**RuntimeException类及其子类**

#### 处理方法

##### 方法一

```java
try {
	/*可能出现异常的代码，可以是多行代码
	若一行代码出错，其下代码不会运行*/    
} catch (Exception e) {
    /*对异常的处理代码*/
}
```

- 如果确定具体的异常类型，也可将`Exception`改为其具体的子类，对象名随便起

- try后可跟多个catch语句，每个catch中异常类不同，不确定具体异常类型时可以这样写（不常用）

  ```java
  // 常用方法
  try {
      /*code*/
  } catch (Exception e) {
      if (e instanceof <具体异常类>) {
      	/*code*/
      }
      if (e instanceof <具体异常类>) {
          /*code*/
      }
  }
  ```

  

- 异常在catch中得到处理，try catch代码块后面的代码会被执行

- 异常最好在调用端处理，别在被调用端处理。（就好比公司职员工作出错未上报，如果未自行处理妥当，后期会出大错。如果由上司统筹处理会减少出错概率）

##### 方法二

```java
try {
    /*code*/
} finally {
    /*code*/
}
```

- 出现异常将会被抛给调用端
- finally中的代码一定会被执行，即使try中代码无异常或无异常且有return语句

##### 方法三

```java
try {
    /*code*/
} catch (Exception e) {
    /*code*/
} finally {
    /*code*/
}
```

- 与方法二的区别就是处理了异常

- finally特性

  ```java
  public static int divide (int a, int b) {
      int c = 0;
      try {
          c = a/b;
          return c;
      } catch (Exception e) {
          c = 4;
          return c;
      } finally {
          c = 5;
          return c;
      }
  }
  public static void main(String[] args) {
      int x = divide(10,0);
      int y = divide(10,1);
  }
  /*x、y的结果都是5，finally是唯一一个可以改变返回值的语句
  如果finally中没有返回语句，则x=4，y=10*/
  ```

##### 方法四

throw和throws（待整理）

### 2. 编译期异常

#### 特点

**必须在编写代码时处理，否则无法编译。**

#### 包含的异常类

**除RuntimeException及其子类之外的所有Exception子类**

#### 产生原因

**在Java提供的API中有的类或方法会自动抛出异常，在调用时如果没有接收异常对象就会报错**

#### 处理方法

**使用try catch代码块或者throw语句处理即可**

### 3. 自定义异常

**自己的项目中可能会有有一些跟业务相关的异常，Java提供的API中无此异常类**

#### 定义规则

**项目中出现的异常99%都是运行时异常，自定义的异常类只需要继承RuntimeException类即可**

#### 举例

```java
public class TestException extends RuntimeException {
    public TestException () {
        // 调用父类构造器
        super();
    }
}
```

```java
public class Test {
    puublic void work (int a) {
        if(a > 5)
            throw new TestException();
    }
    public static void main(String[] args) {
        try {
            work(10);
        }catch (TestException t) {
            work(4);
        }
    }
}
```

